version: '3'
services:

    apache-php:
        build:
            context: ./
            dockerfile: dockerfile-apache-php
        container_name: apache-php
        ports:
         - '80:80'
         - '443:443'
        volumes:
         - '..:/var/www/html'

    mariadb:
        image: mariadb
        container_name: mariadb
        ports:
          - '3306:3306'
        logging:
            driver: none
        environment:
            MYSQL_ROOT_PASSWORD: example

    redis:
        image: redis
        container_name: redis
        ports:
          - '6379:6379'
        logging:
            driver: none

    #mongo:
    #    image: mongo
    #    container_name: mongo
    #    ports:
    #      - '27017:27017'

    #scylla:
    #    image: scylladb/scylla
    #    container_name: scylla
    #    ports:
    #      - '9160:9160'

    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        ports:
         - '5672:5672'
         - '15672:15672'
        logging:
            driver: none

    #elasticsearch:
    #    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    #    container_name: elasticsearch
    #    ports:
    #     - '9200:9200'
